-- 계약서 저장 테이블
CREATE TABLE IF NOT EXISTS contracts (
  id TEXT PRIMARY KEY,
  title TEXT,
  contract_date TEXT,
  provider_company TEXT,
  provider_rep TEXT,
  provider_phone TEXT,
  provider_email TEXT,
  bank_name TEXT,
  bank_account TEXT,
  bank_holder TEXT,
  services TEXT,
  extra_service TEXT,
  setup_fee INTEGER,
  monthly_fee INTEGER,
  vat_type TEXT,
  payment_method TEXT,
  start_date TEXT,
  payment_day INTEGER,
  initial_amount INTEGER,
  monthly_amount INTEGER,
  sms_agree INTEGER DEFAULT 0,
  client_company TEXT,
  client_name TEXT,
  client_phone TEXT,
  client_email TEXT,
  client_address TEXT,
  client_signature TEXT,
  status TEXT DEFAULT 'draft',
  created_at TEXT DEFAULT (datetime('now')),
  signed_at TEXT
);
